SELECT CAR_ID, AVERAGE_DURATION
FROM (
    SELECT CAR_ID,
        ROUND(
            AVG(
                DATEDIFF(END_DATE, START_DATE) + 1
            ), 1
        )
         AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    -- 평균 대여 기간이 7일 이상인 자동차
    GROUP BY CAR_ID
) AS C
WHERE AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;
