WITH FRONT_SKILL AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
    GROUP BY CATEGORY
)
SELECT ID, EMAIL,FIRST_NAME, LAST_NAME
FROM (
    DEVELOPERS AS D,
    FRONT_SKILL AS F
)
WHERE D.SKILL_CODE & F.CODE > 0
ORDER BY D.ID ASC;