SELECT SUM(G.SCORE) AS SCORE,
    E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM (
    HR_EMPLOYEES as E
    JOIN HR_GRADE AS G
    ON E.EMP_NO = G.EMP_NO
)
GROUP BY G.YEAR, G.EMP_NO, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
HAVING G.YEAR = 2022
ORDER BY SCORE DESC
LIMIT 1;