SELECT B.BOOK_ID, A.AUTHOR_NAME,
    DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM ((
        SELECT BOOK_ID, PUBLISHED_DATE, AUTHOR_ID
        FROM BOOK
        WHERE CATEGORY = "경제"
    ) AS B
    JOIN AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID
)
ORDER BY B.PUBLISHED_DATE ASC;

